# Generated by Django 3.1.3 on 2021-02-12 11:19

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.PathAndRename('/uploads')),
        ),
        migrations.AlterField(
            model_name='post',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.PathAndRename('/uploads')),
        ),
    ]
