# Generated by Django 3.1.3 on 2021-02-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210212_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
