# Generated by Django 3.1.3 on 2021-05-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fb_comment_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
