# Generated by Django 3.1.3 on 2021-02-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='post',
            new_name='posts',
        ),
    ]
